name: OceManaBar
main: me.oceanor.OceManaBar.OceManaBar
version: 2.0
depend: [Spout,MagicSpells]
permissions:
    ocemanabar.show:
        description: show/hide mana bar to players
        default: true 