name: OceManaBar
main: me.oceanor.OceManaBar.OceManaBar
version: 1.0
depend: [Spout,MagicSpells]
commands:
    manabar:
        description: Comando per OceManaBar.
        usage: /<command> reload
    ocemanabar:
        description: comando alternativo per OceManaBar.
        usage: /<command> reload
permissions:
    ocemanabar.admin:
        description: allow the usage of all commands
        default: false
    ocemanabar.reload:
        description: allow the player to reload config
        default: false
    ocemanabar.show:
        description: show/hide mana bar to players
        default: true